### ISSUE TITLE
nodebb v2.0.0 have conflict

### ISSUE THREAD

**Issue by yizhen20** [exsilium/nodebb-plugin-mermaid#4]
![image](https://user-images.githubusercontent.com/62855365/168933870-a0e305bd-e1ae-4a5b-8c7d-c24e71d71d91.png)
Many thanks to exsilium，nodebb has now entered the next version
nodebb-plugin-mermaid Although it works fine，But it affects the page refresh progress bar
The progress bar will always exist and not disappear，until i uninstall nodebb-plugin-mermaid

**Comment by exsilium** [comment]
Thank you for the comment and additional notes @yizhen20 , I will upgrade and test this issue out. Stay tuned.

**Comment by exsilium** [comment]
Hi @yizhen20 , a new version `v0.3.0` has been release, please let me know how it performs for you. Cheers!

**Comment by exsilium** [comment]
👆 Correction, `v0.3.1` is now published for testing.

**Comment by yizhen20** [comment]
Thank you @exsilium v0.3.1 is working perfectly on my environment！
No serious bugs have been found so far，
I hope that the ecology after nodebb v2.0 will get better and better！

**Comment by yizhen20** [comment]
> 👆 Correction, `v0.3.1` is now published for testing.

Thank you @exsilium v0.3.1 is working perfectly on my environment！
No serious bugs have been found so far，
I hope that the ecology after nodebb v2.0 will get better and better！

**Comment by exsilium** [comment]
Thank you for the feedback, @yizhen20 . Closing the issue. Cheers!
